version: '2'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        USER: ${USER}
        UID: ${UID}
    ports:
      - "${SERVER_HOST}:80:8000"
    cpu_shares: 256
    mem_limit: 1024M
    env_file: .env
    environment:
      - PGUSER=${APP}${ENV}
      - PGDATABASE=${APP}${ENV}
      - PGPASSWORD=${PGPASSWORD}
      - DATABASE_URL=psql://${APP}${ENV}:${PGPASSWORD}@db/${APP}${ENV}
