# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.CharField(max_length=255, null=True, verbose_name='Tweeter')),
                ('facebook', models.CharField(max_length=255, null=True, verbose_name='Facebook')),
                ('google', models.CharField(max_length=255, null=True, verbose_name='Google+')),
                ('vk', models.CharField(max_length=255, null=True, verbose_name='Vkontakte')),
                ('profile_photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='profile', verbose_name='Photo')),
                ('authentication_hash', models.CharField(max_length=255, verbose_name='hash')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Adress')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
